version: '2'

services:
  app:
    image: abakpress/ruby:${RUBY_IMAGE_TAG}
    environment:
      - BUNDLE_PATH=/bundle/${DOCKER_RUBY_VERSION}
      - SSH_AUTH_SOCK=/ssh/auth/sock
      - TEST_DB_HOST=db
      - TEST_DB_NAME=${POSTGRES_DB}
      - TEST_DB_USERNAME=postgres
    command: bash
    depends_on:
      - db

  db:
    image: abakpress/postgres:${POSTGRES_IMAGE_TAG}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
