test:
  adapter: postgresql
  database: <%= ENV.fetch("TEST_DB_NAME", "ci") %>
  username: <%= ENV.fetch("TEST_DB_USERNAME", "docker") %>
  host: <%= ENV.fetch("TEST_DB_HOST", "localhost") %>
  min_messages: warning
